=== cramo/autom/ProjetXML/dtd2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT produits (produit*)>
<!ELEMENT produit (nom, desc, prix, qté)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT qté (#PCDATA)>
<!ATTLIST produit id ID #REQUIRED>
<!ATTLIST produit categorie (jouet|livre) #REQUIRED>

=== cramo/autom/ProjetXML/dtd1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- -->
<!DOCTYPE produits SYSTEM "dtd2.dtd">
<produits>
	<produit id="A1" categorie="jouet">
		<nom>test</nom>
		<desc>test</desc>
		<prix>test</prix>
		<qté>test</qté>
	</produit>
	<produit id="A2" categorie="livre">
		<nom>test</nom>
		<desc>test</desc>
		<prix>test</prix>
		<qté>test</qté>
	</produit>
</produits>
